---
Curso: Formação Cientista de Dados 

Prof.: Fernando Amaral

Aluno: Adriano Show

Data: 09/07/2022 - 23:41

Assunto: Estruturas de Dados
---

---
 Trabalhando com Vetores
---
```{r}
X  = c(1,2,3,4,5,6)  
X 
X[1]
X[1] = 10
X[1]
```
---
 Trabalhando com Vetores de outros tipos
---
```{r}
Y = c("a","b","c","d")
Y
Z = c(1L,2L,3L)
Z
class(Z)
```
---
Trabalhando com Matrizes
---
```{r}
VADeaths
colnames(VADeaths)
rownames(VADeaths)
```
---
Trabalhando com Matrizes 2
---
```{r}
#só coluna 1
VADeaths[,1]
#so linha 1
VADeaths[1,]
#linhas 1 até 3
VADeaths[1:3,]
VADeaths[c(1,3,5),]
```
---
Data Frame
---
```{r}
longley
#funcina como matriz
longley[,1:3]
#acessar coluna com $
longley$Unemployed
#ou nome
longley['Unemployed']
```
---
Listas
---
```{r}
ability.cov 
#acessando elementos
ability.cov$cov
ability.cov[1]
#verificando que são objetos diferentes
class( ability.cov$cov)
class( ability.cov$center)
#acesando elemento dentro da lista
ability.cov$cov[,1:3]
```
---
Fatores
---
```{r}
#fatores
state.region
```

