---
Curso: Formação Cientista de Dados 

Prof.: Fernando Amaral

Aluno: Adriano Show

Data: 15/07/2022 - 18:50

Assunto: Faça você mesmo
---

```{r}
#paleta de cores
library("RColorBrewer")
#install.packages("RColorBrewer")
```


```{r}
# importando os DADOS para variavel mydados
mydados = read.csv('dados.csv', sep=";")
# explorando os dados
head(mydados)
```


```{r}
#explorando resumo dos dados 
summary(mydados$VALOREMPENHO)
summary(mydados$PIB)
```


```{r warning=FALSE}
#Alguns gráficos
boxplot(mydados$VALOREMPENHO, main="Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"), outline = F )

boxplot(mydados$PIB ,main="Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline = F )

hist(mydados$VALOREMPENHO,main="Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"))

hist(mydados$PIB,main="Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline = F )
```


```{r}
#Busca os maiores empenhos
#executar com ctrl + shif + enter
Mempenho = head(mydados[order(-mydados$VALOREMPENHO),],10)
barplot(Mempenho$VALOREMPENHO, col=brewer.pal(n = 10, name = "RdBu"),las=2,main = "Maiores Empenhos")
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "RdBu"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```


```{r}
#Maiores Pibs
#executar com ctrl + shif + enter
Mpibs =   head(mydados[order(-mydados$PIB),],10)
barplot(Mpibs$PIB,col=brewer.pal(n = 10, name = "Spectral"),las=2,main = "Maiores PIBS")
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "Spectral"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```


```{r}
#Relação entre PIB e empenho
#Calcula qual % de PIB foi empenhado
mydados$PROPORCAO =   mydados$VALOREMPENHO  / mydados$PIB 
Mprop = head(mydados[order(-mydados$PROPORCAO),],10)
barplot(Mprop$PROPORCAO,col=brewer.pal(n = 10, name = "Set2"),las=2,main = "Maiores Gastos em Proporção ao PIB")
legend("topright",legend=Mprop$MUNICIPIO,col = brewer.pal(n = 10, name = "Set2"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()

```
